# Generated by Django 5.2.11 on 2026-02-08 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_catalog_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "db_table": "content_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Имя (для гостя)")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email (для гостя)")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], verbose_name="Оценка"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Текст отзыва")),
                ("is_approved", models.BooleanField(default=False, verbose_name="Одобрен")),
                ("is_verified_purchase", models.BooleanField(default=False, verbose_name="Покупка подтверждена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "content_review",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["product"], name="content_rev_product_3b1e96_idx"),
                    models.Index(fields=["is_approved"], name="content_rev_is_appr_1a822c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("product", "user"),
                        name="content_review_unique_product_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True), ("email__isnull", False)),
                        fields=("product", "email"),
                        name="content_review_unique_product_email",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("content", models.TextField(verbose_name="Содержание")),
                ("excerpt", models.TextField(blank=True, null=True, verbose_name="Краткое описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/news/%Y/%m/", verbose_name="Изображение"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("news", "Новости"), ("guide", "Гайды"), ("review", "Обзоры"), ("other", "Другое")],
                        max_length=32,
                        null=True,
                        verbose_name="Категория",
                    ),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("is_featured", models.BooleanField(default=False, verbose_name="В избранном")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("views_count", models.IntegerField(default=0, verbose_name="Просмотры")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Meta title (SEO)"),
                ),
                ("meta_description", models.TextField(blank=True, null=True, verbose_name="Meta description (SEO)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="news", to="content.tag", verbose_name="Теги"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "db_table": "content_news",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_new_slug_2e5c33_idx"),
                    models.Index(fields=["is_published"], name="content_new_is_publ_159a3d_idx"),
                    models.Index(fields=["is_featured"], name="content_new_is_feat_bf4175_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("content", models.TextField(help_text="HTML допускается", verbose_name="Содержание")),
                ("excerpt", models.TextField(blank=True, null=True, verbose_name="Краткое описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/articles/%Y/%m/", verbose_name="Изображение"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("news", "Новости"), ("guide", "Гайды"), ("review", "Обзоры"), ("other", "Другое")],
                        max_length=32,
                        null=True,
                        verbose_name="Категория",
                    ),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("views_count", models.IntegerField(default=0, verbose_name="Просмотры")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Meta title (SEO)"),
                ),
                ("meta_description", models.TextField(blank=True, null=True, verbose_name="Meta description (SEO)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="articles", to="content.tag", verbose_name="Теги"),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "db_table": "content_article",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_art_slug_d82f31_idx"),
                    models.Index(fields=["is_published"], name="content_art_is_publ_3d120d_idx"),
                    models.Index(fields=["published_at"], name="content_art_publish_09f985_idx"),
                ],
            },
        ),
    ]
