# Generated by Django 4.2.26 on 2026-02-07 12:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_catalog_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_store_and_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер заказа')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], max_length=20, verbose_name='Тип доставки')),
                ('delivery_address', models.JSONField(blank=True, default=dict, help_text='city, street, house, apartment, postal_code', verbose_name='Адрес доставки')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличными'), ('card_on_delivery', 'Картой при получении'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма заказа')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость доставки')),
                ('bonus_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Списано бонусов')),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Начислено бонусов')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.store', verbose_name='Магазин (самовывоз)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255, verbose_name='Название на момент заказа')),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена на момент заказа')),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма по позиции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'db_table': 'orders_orderitem',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'), models.Index(fields=['product'], name='orders_orde_product_32ff41_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
    ]
