# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_order_and_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="consent_personal_data",
            field=models.BooleanField(
                default=False,
                verbose_name="Согласие на обработку персональных данных",
            ),
        ),
    ]
