# Generated by Django 4.2.26 on 2026-03-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_manager_model'),
        ('orders', '0003_managerrating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='managerrating',
            new_name='orders_mana_rating_b57f21_idx',
            old_name='orders_mana_rating_8a1f2b_idx',
        ),
        migrations.RenameIndex(
            model_name='managerrating',
            new_name='orders_mana_created_0c3348_idx',
            old_name='orders_mana_created_9c3d4e_idx',
        ),
        migrations.AddField(
            model_name='managerrating',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='stores.manager', verbose_name='Менеджер'),
        ),
        migrations.AddIndex(
            model_name='managerrating',
            index=models.Index(fields=['manager'], name='orders_mana_manager_581caf_idx'),
        ),
    ]
