# Generated by Django 5.2.11 on 2026-02-08 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_catalog_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Будет сохранён в верхнем регистре",
                        max_length=64,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Процент"), ("fixed", "Фиксированная сумма")],
                        max_length=16,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Значение скидки"),
                ),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True, verbose_name="Макс. использований")),
                ("used_count", models.PositiveIntegerField(default=0, verbose_name="Использовано")),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Мин. сумма заказа"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Начало")),
                ("end_date", models.DateTimeField(verbose_name="Окончание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "db_table": "promotions_promocode",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="promotions__code_2587f5_idx"),
                    models.Index(fields=["start_date"], name="promotions__start_d_22bec5_idx"),
                    models.Index(fields=["end_date"], name="promotions__end_dat_da5544_idx"),
                    models.Index(fields=["is_active"], name="promotions__is_acti_9af606_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="promotions/%Y/%m/", verbose_name="Изображение"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Процент"), ("fixed", "Фиксированная сумма")],
                        max_length=16,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Значение скидки"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Начало")),
                ("end_date", models.DateTimeField(verbose_name="Окончание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="products.category", verbose_name="Категории"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="products.product", verbose_name="Товары"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "db_table": "promotions_promotion",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["start_date"], name="promotions__start_d_f657f9_idx"),
                    models.Index(fields=["end_date"], name="promotions__end_dat_7e6c7a_idx"),
                    models.Index(fields=["is_active"], name="promotions__is_acti_fc6f30_idx"),
                ],
            },
        ),
    ]
