# Generated by Django 5.2.11 on 2026-02-08 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingProductRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255, verbose_name="Название товара")),
                ("contact_phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новая"), ("processed", "В работе"), ("closed", "Закрыта")],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missing_product_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на отсутствующий товар",
                "verbose_name_plural": "Заявки на отсутствующий товар",
                "db_table": "crm_missingproductrequest",
                "ordering": ["-created_at"],
            },
        ),
    ]
