# Generated by Django 4.2.26 on 2026-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_missingproductrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingproductrequest',
            name='contact_name',
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Имя"
            ),
        ),
    ]
