# Generated by Django 4.2.26 on 2026-03-08 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_store_and_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок вывода')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'db_table': 'stores_manager',
                'ordering': ['store', 'order', 'name'],
            },
        ),
    ]
